### ISSUE TITLE
Reopening loads journals out of order

### ISSUE THREAD

**Issue by Silarn** [EDDiscovery/EDD-EDMC#3]
I only noticed this because I was working on a plugin and reopening the tool to reload the code.

Normally, the plugin should clear out system data when you hyperjump and start fresh, but after reloading while EDD remains open, it seems to be loading up journals in a somewhat random order.

This causes system data for previous systems to remain loaded until you jump again and get a new journal entry and force it to reclear the old data.

**Comment by robbyxp1** [comment]
So, the way its designed, that EDD/EDDLite reads the last two journals written and sends them to EDD-EDMC.  This is to fill in its knowledge of the current state - this is the same as EDMC itself does (except it only reads the last which would not cover the journal continue situation).

EDMC does not clear its state on a hyperjump, it just updates its values in monitor.py.

I'm not sure what is wrong from your description.

**Comment by robbyxp1** [comment]
Closing, i can't see anything wrong with its operation, and no more feedback to clarify.
