### ISSUE TITLE
Virus Total tells eddedmcwin.exe is a virus

### ISSUE THREAD

**Issue by netchild** [EDDiscovery/EDD-EDMC#5]
Hi,

I downloaded the latest version and Windows Defender directly quarantined it. On VirusTotal 16 scan engines think it is a virus. You may want to check if the release is ok and if it is ok do something about the false positive.

Bye,
Alexander.

**Comment by Eahlstan** [comment]
It's a false positive, Microsoft already fixed their signature.

![Screenshot 2021-04-10 175141](https://user-images.githubusercontent.com/59618179/114305567-ede8c300-9ad8-11eb-918c-cab1524d20dc.JPG)

**Comment by robbyxp1** [comment]
![image](https://user-images.githubusercontent.com/6573992/114305429-18824e00-9ad0-11eb-87b7-cedb4b93ad89.png)

So 5 minor virus engines detect it, one or two always do. 

There is nothing much you can do about false positives.  Virus engines are a law to themselves.

Windows defender had a hickup yesterday over the python components in this program - i think its been fixed.

Closing.

**Comment by eitan-j** [comment]
This still seems to still be an issue. The installer itself (EDD-EDMC-1.2.0.exe) is only detected as malware by two "security vendors". However, eddmc.exe and eddmcwin.exe, which appear in C:\Program Files\EDD-EDMC once it is installed, are detected by 5 and 18 "security vendors", respectively, including big names like Mcafee, Bitdefender, and Avast/AVG.

Virustotal Links:
[EDD-EDMC-1.2.0.exe](https://www.virustotal.com/gui/file/35ace4d3d34d2bea460a044f0d3185e60864521f5a7efe08aeaa72c54da8325d/detection)
[eddedmc.exe](https://www.virustotal.com/gui/file/92c4814e43bb9b658c33feb38bcfa66300895a7b11066abcef063fa5dbdcb54e/detection)
[eddmcwin.exe](https://www.virustotal.com/gui/file/c1d0920cf1ab1284f42c6bcd66fede7eaf79c90cb272a51b75c1301470f72224/detection)

**Comment by robbyxp1** [comment]
Not much can be done, i can't reengineer the thing just because an antivirus thinks its bad.  Its been using the same stuff for a year now.

thanks
